server:
  port: 8081

spring:
  application:
    name: springcloud-provider
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.6.13:8761/eureka/
